In [1]:
## Baseling XGBoost

In [3]:
# Preparing Notebook for experiment
%load_ext autoreload
%autoreload 2

In [4]:
# Importing Packages
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from joblib import dump 

In [6]:
# Getting data
from ds.data.sets import load_sets
X_train, y_train, X_val, y_val, X_test, y_test = load_sets(path='../data/processed/')


In [8]:
# Convert the data to DMatrix format
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)
dtest = xgb.DMatrix(X_test, label=y_test)

In [25]:
# Define Parameters

num_classes = 10

params = {
    'objective': 'multi:softmax',
    'num_class': num_classes,
    'eval_metric': 'mlogloss',
    'max_depth': 3,
    'learning_rate': 0.1,
    'subsample': 0.8,
    'colsample_bytree': 0.8
}

In [26]:
# Create an XGBoost classifier object with the defined parameters
xgb_model = xgb.XGBClassifier(**params)

In [27]:
# Train the model on the training data
xgb_model.fit(X_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_class=103, num_parallel_tree=None, objective='multi:softmax', ...)

In [32]:
# Analytics
from ds.models.performance import evaluate_model_multi
evaluate_model_multi(xgb_model, X_test, y_test)


/home/marcosulser/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Validation Set Metrics:
Accuracy: 0.2765
Precision: 0.3257
Recall: 0.2765
F1-Score: 0.2312
Confusion Matrix (Validation Set):
[[   9   74   36 ...    0    5  106]
 [   0 3965   28 ...    0    2  116]
 [   0  252  614 ...    0   27  354]
 ...
 [   0    0    0 ...  149    0    0]
 [   0   10   23 ...    0  470   22]
 [   0  254  101 ...    0   90 1471]]


In [34]:
# Saving Model
dump(xgb_model,  '../models/base_mod_Marco.joblib')

['../models/base_mod_Marco.joblib']